-- 코드를 입력하세요
-- 2022년 1월의 도서 판매 데이터를 기준
-- 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력하는 SQL문을 작성
SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN AUTHOR A
ON(B.AUTHOR_ID=A.AUTHOR_ID)
LEFT JOIN BOOK_SALES S
ON(S.BOOK_ID=B.BOOK_ID)
WHERE DATE_FORMAT(S.SALES_DATE,'%Y-%m')='2022-01'
GROUP BY A.AUTHOR_ID,B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC