-- 코드를 입력하세요
-- 평균 일일 대여 요금을 출력 , 소수 첫 번째 자리에서 반올림
-- 컬럼명은 AVERAGE_FEE -> AS
-- SELECT ROUND(AVG(DAILY_FEE),1) AS AVERAGE_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = 'SUV'
SELECT ROUND(AVG(DAILY_FEE),0) AS AVERAGE_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = 'SUV'