-- 코드를 작성해주세요
SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO 
WHERE ITEM_ID NOT IN (
    SELECT T.PARENT_ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T
    ON(I.ITEM_ID=T.ITEM_ID)
    WHERE T.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC