-- 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
SELECT P.PRODUCT_CODE,SUM(P.PRICE * IFNULL(O.SALES_AMOUNT,0)) AS SALES
FROM PRODUCT P
LEFT JOIN OFFLINE_SALE O
ON(P.PRODUCT_ID=O.PRODUCT_ID)
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE