-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
WITH A AS(SELECT C.CAR_ID, C.car_type,C.daily_fee
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON(C.CAR_ID=H.CAR_ID)
WHERE C.CAR_ID  NOT IN (
    SELECT C.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON(C.CAR_ID=H.CAR_ID)
    WHERE (C.CAR_TYPE ='세단' or C.CAR_TYPE='SUV')
    AND( H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
    )
) AND (C.CAR_TYPE ='세단' or C.CAR_TYPE='SUV')
GROUP BY C.CAR_ID
)
,B AS (SELECT A.CAR_ID,A.CAR_TYPE,A.DAILY_FEE*30*(100-R.DISCOUNT_RATE)/100 AS FEE
FROM A 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN R
ON (A.CAR_TYPE =R.CAR_TYPE)
WHERE INSTR(R.DURATION_TYPE,'30')
)

SELECT CAR_ID,CAR_TYPE,FLOOR(FEE) AS FEE FROM B
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC