-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차

WITH A AS(
    SELECT DISTINCT C.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON(C.CAR_ID=H.CAR_ID)
    WHERE (CAR_TYPE='세단' OR CAR_TYPE='SUV') AND (
        (H.START_DATE<='2022-11-30') AND (H.END_DATE>='2022-11-01')
    )
)



SELECT DISTINCT C.CAR_ID,C.CAR_TYPE,FLOOR(C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON(C.CAR_ID=H.CAR_ID)
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON(C.CAR_TYPE=D.CAR_TYPE)
WHERE (C.CAR_TYPE='세단' OR C.CAR_TYPE='SUV') AND INSTR(D.duration_type,'30')
    AND NOT EXISTS(
        SELECT 1
        FROM A
        WHERE A.CAR_ID=C.CAR_ID
    )
    AND C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100>=500000 AND C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100<2000000
ORDER BY FEE DESC,C.CAR_TYPE ASC, C.CAR_ID DESC


