-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차

WITH A AS (SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
WHERE NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
        AND H.CAR_ID = C.CAR_ID
) AND (C.CAR_TYPE ='세단' or C.CAR_TYPE='SUV')
)
,B AS (SELECT C.CAR_ID,C.CAR_TYPE,FLOOR(C.DAILY_FEE * 30 /100 * (100-R.DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN R
ON(C.CAR_TYPE = R.CAR_TYPE)
WHERE C.CAR_ID IN (SELECT CAR_ID FROM A) AND INSTR(R.DURATION_TYPE,'30')
GROUP BY C.CAR_ID
)
SELECT * FROM B WHERE FEE<2000000 AND FEE>=500000
ORDER BY FEE DESC, CAR_TYPE,CAR_ID DESC