-- 코드를 입력하세요
-- 중고 거래 게시물을 3건 이상 등록한 사용자
SELECT B.WRITER_ID AS USER_ID,G.NICKNAME,CONCAT(G.STREET_ADDRESS1,' ',G.STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTRING(TLNO,1,3),'-',SUBSTRING(TLNO,4,4),'-',SUBSTRING(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_USER G
ON(B.WRITER_ID= G.USER_ID)
GROUP BY B.WRITER_ID
HAVING COUNT(*)>=3
ORDER BY USER_ID DESC
