-- 코드를 입력하세요
SELECT I.ANIMAL_ID,I.ANIMAL_TYPE,I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON(I.ANIMAL_ID=O.ANIMAL_ID)
WHERE INSTR(I.SEX_UPON_INTAKE,'INTACT')
AND (INSTR(O.SEX_UPON_OUTCOME,'Spayed') OR INSTR(O.SEX_UPON_OUTCOME,'Neutered'))
ORDER BY I.ANIMAL_ID