-- 코드를 작성해주세요
-- 물고기의 종류 별 물고기의 이름과 잡은 수를 출력
SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO I
LEFT JOIN FISH_NAME_INFO N
ON(I.FISH_TYPE= N.FISH_TYPE)
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC
