-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율
-- (=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
-- 년, 월 별로 출력하는 SQL문을 작성

-- SELECT COUNT(O.ONLINE_SALE_ID IS NOT NULL)/COUNT(DISTINCT U.USER_ID)
-- 111 186

-- 이게 2021년 가입한 전체 회원 수
-- SELECT COUNT(DISTINCT U.USER_ID)
-- FROM USER_INFO U
-- LEFT JOIN ONLINE_SALE  O
-- ON(U.USER_ID = O.USER_ID)
-- WHERE YEAR(U.JOINED)=2021

SELECT YEAR(SALES_DATE) AS YEAR ,MONTH(SALES_DATE) AS MONTH,COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS
,ROUND(COUNT(DISTINCT U.USER_ID)/(
    SELECT COUNT(DISTINCT U.USER_ID)
    FROM USER_INFO U
    LEFT JOIN ONLINE_SALE  O
    ON(U.USER_ID = O.USER_ID)
    WHERE YEAR(U.JOINED)=2021),1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE  O
ON(U.USER_ID = O.USER_ID)
WHERE YEAR(U.JOINED)=2021
GROUP BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE)