-- 각 세대별 자식이 없는 개체의 수(COUNT)와 세대(GENERATION)를 출력하는 SQL문을 작성
-- 1세대


WITH RECURSIVE GEN AS (
    SELECT ID,PARENT_ID,1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT D.ID,D.PARENT_ID,G.GENERATION+1
    FROM ECOLI_DATA D
    JOIN GEN G
    ON D.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT,GENERATION FROM GEN G
LEFT JOIN ECOLI_DATA D
ON(G.ID=D.PARENT_ID)
WHERE D.ID IS NULL
GROUP BY G.GENERATION