-- CAR_RENTAL_COMPANY_RENTAL_HISTORY

WITH A AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16'>=START_DATE AND '2022-10-16'<=END_DATE
)
SELECT DISTINCT CAR_ID,
CASE
    WHEN CAR_ID IN (SELECT * FROM A) THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC

