-- 각 분기(QUARTER)별 분화된 대장균의 개체의 총 수(ECOLI_COUNT)를 출력하는 SQL 문을 작성
-- 분기에 대해 오름차순으로 정렬
WITH A AS (SELECT *,
CASE
    WHEN MONTH(DIFFERENTIATION_DATE)>=10 THEN '4Q'
    WHEN MONTH(DIFFERENTIATION_DATE)>=7 THEN '3Q'
    WHEN MONTH(DIFFERENTIATION_DATE)>=4 THEN '2Q'
    ELSE '1Q'
    END AS QUARTER
FROM ECOLI_DATA 
)
SELECT QUARTER,COUNT(ID) AS ECOLI_COUNT
FROM A
GROUP BY QUARTER
ORDER BY QUARTER