-- 코드를 입력하세요
-- 생산일자가 2022년 5월인 식품들
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON(P.PRODUCT_ID = O.PRODUCT_ID)
WHERE DATE_FORMAT(O.PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID