-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성
-- DATEDIFF(H.END_DATE,H.START_DATE) +1 AS DATE_DIFF
WITH E AS(
    SELECT C.CAR_TYPE, 
    CASE 
        WHEN DATEDIFF(H.END_DATE,H.START_DATE) +1>=90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE,H.START_DATE) +1>=30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE,H.START_DATE) +1>=7 THEN '7일 이상'
        ELSE NULL
        END AS DATE_DIFF
    , C.DAILY_FEE * (DATEDIFF(H.END_DATE,H.START_DATE) +1) AS FEE
    ,H.HISTORY_ID
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON(C.CAR_ID=H.CAR_ID)
    WHERE C.CAR_TYPE='트럭'
)
-- 이 테이블을 토대로 

SELECT E.HISTORY_ID,
FLOOR(IF(DISCOUNT_RATE IS NULL,FEE,FEE*(100-discount_rate)/100)) AS FEE
FROM E
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON ((E.CAR_TYPE=D.CAR_TYPE) AND (E.DATE_DIFF = D.DURATION_TYPE))
ORDER BY FEE DESC,HISTORY_ID DESC
