-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력

WITH A AS (
    SELECT 
    CASE
        WHEN INSTR(DURATION_TYPE,'90') THEN '90'
        WHEN INSTR(DURATION_TYPE,'30') THEN '30'
        ELSE '7'
        END AS duration_type,
    DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE='트럭'
)

SELECT H.HISTORY_ID,
CASE
    WHEN (DATEDIFF(H.END_DATE,START_DATE)+1) >= 90
    THEN FLOOR((DATEDIFF(H.END_DATE,START_DATE)+1) * C.DAILY_FEE
    *(100- (SELECT DISCOUNT_RATE FROM A WHERE duration_type='90'))/100)
    WHEN (DATEDIFF(H.END_DATE,START_DATE)+1) >= 30
    THEN FLOOR((DATEDIFF(H.END_DATE,START_DATE)+1) * C.DAILY_FEE
    *(100- (SELECT DISCOUNT_RATE FROM A WHERE duration_type='30'))/100)
    WHEN (DATEDIFF(H.END_DATE,START_DATE)+1) >= 7
    THEN FLOOR((DATEDIFF(H.END_DATE,START_DATE)+1) * C.DAILY_FEE
    *(100- (SELECT DISCOUNT_RATE FROM A WHERE duration_type='7'))/100)
    ELSE FLOOR((DATEDIFF(H.END_DATE,START_DATE)+1) * C.DAILY_FEE)
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON(C.CAR_ID=H.CAR_ID)
WHERE C.CAR_TYPE='트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC