-- 코드를 입력하세요
-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL문을 작성

SELECT A.APNT_NO,P.PT_NAME,P.PT_NO,D.MCDP_CD,D.DR_NAME,A.APNT_YMD
FROM APPOINTMENT A
LEFT JOIN PATIENT P
ON(P.PT_NO=A.PT_NO)
LEFT JOIN DOCTOR D
ON(A.MDDR_ID= D.DR_ID)
WHERE A.MCDP_CD='CS' AND A.APNT_CNCL_YN='N' AND DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d')='2022-04-13'
ORDER BY A.APNT_YMD