-- 코드를 입력하세요
WITH RECURSIVE R AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM R
    WHERE HOUR<23
)

SELECT R.HOUR,COUNT(O.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS O
RIGHT JOIN R
ON(HOUR(O.DATETIME) = R.HOUR)
GROUP BY R.HOUR