--  사원별 성과금 정보를 조회
--  사번, 성명, 평가 등급, 성과금을 조회하는 SQL문을 작성

SELECT E.EMP_NO,E.EMP_NAME,
CASE
    WHEN AVG(G.SCORE)>=96 THEN 'S'
    WHEN AVG(G.SCORE)>=90 THEN 'A'
    WHEN AVG(G.SCORE)>=80 THEN 'B'
    ELSE 'C'
    END AS GRADE,
CASE
    WHEN AVG(G.SCORE)>=96 THEN SAL*0.2
    WHEN AVG(G.SCORE)>=90 THEN SAL*0.15
    WHEN AVG(G.SCORE)>=80 THEN SAL*0.1
    ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
ON (E.EMP_NO=G.EMP_NO)
GROUP BY E.EMP_NO
ORDER BY E.EMP_NO