-- 아이템의 희귀도가 'RARE'인 아이템들의 모든 다음 업그레이드 아이템의
-- 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)를 출력

-- ~의 자식아이템을
SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN(
    SELECT T.ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T
    ON(I.ITEM_ID=T.PARENT_ITEM_ID)
    WHERE I.RARITY='RARE'
)
ORDER BY ITEM_ID DESC

