-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서
-- 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력
WITH A AS (SELECT CAR_ID, COUNT(*) AS COUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE DATE_FORMAT(START_DATE,'%Y-%m') IN ('2022-08','2022-09','2022-10')
GROUP BY CAR_ID
HAVING COUNT(*)>=5
)
SELECT MONTH(START_DATE) AS MONTH,CAR_ID,COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID FROM A) AND DATE_FORMAT(START_DATE,'%Y-%m') IN ('2022-08','2022-09','2022-10')
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH(START_DATE),CAR_ID DESC