-- 분화된 연도(YEAR), 분화된 연도별 대장균 크기의 편차(YEAR_DEV), 대장균 개체의 ID(ID) 를 출력
-- . 분화된 연도별 대장균 크기의 편차는 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기

WITH A AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    )
    
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,(
    SELECT MAX_SIZE 
    FROM A
    WHERE A.YEAR= YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV
,ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV