-- 코드를 입력하세요
-- 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트를 출력
SELECT DISTINCT R.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR R
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON(R.CAR_ID=H.CAR_ID)
WHERE CAR_TYPE = '세단' AND MONTH(H.START_DATE) =10
ORDER BY R.CAR_ID DESC